/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnalyticsPoint,
  DayStats,
  HTTPValidationError,
  ReminderSchema,
  ResponseGetRemindersApiRemindersGet,
  RoleSchema,
  Timezone,
  UserContext,
  WebUser,
} from '../models/index';
import {
    AnalyticsPointFromJSON,
    AnalyticsPointToJSON,
    DayStatsFromJSON,
    DayStatsToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ReminderSchemaFromJSON,
    ReminderSchemaToJSON,
    ResponseGetRemindersApiRemindersGetFromJSON,
    ResponseGetRemindersApiRemindersGetToJSON,
    RoleSchemaFromJSON,
    RoleSchemaToJSON,
    TimezoneFromJSON,
    TimezoneToJSON,
    UserContextFromJSON,
    UserContextToJSON,
    WebUserFromJSON,
    WebUserToJSON,
} from '../models/index';

export interface CreateUserUserPostRequest {
    webUser: WebUser;
    xTelegramInitData?: string | null;
}

export interface DeleteReminderApiRemindersDeleteRequest {
    telegramId?: number | null;
    telegramId2?: number | null;
    id?: number | null;
    xTelegramInitData?: string | null;
}

export interface GetAnalyticsApiAnalyticsGetRequest {
    telegramId: number;
    xTelegramInitData?: string | null;
}

export interface GetRemindersApiRemindersGetRequest {
    telegramId?: number | null;
    telegramId2?: number | null;
    id?: number | null;
    xTelegramInitData?: string | null;
}

export interface GetRoleUserUserIdRoleGetRequest {
    userId: number;
}

export interface GetStatsApiStatsGetRequest {
    telegramId: number;
    xTelegramInitData?: string | null;
}

export interface GetTimezoneTimezoneGetRequest {
    xTelegramInitData?: string | null;
}

export interface PatchReminderApiRemindersPatchRequest {
    reminderSchema: ReminderSchema;
    xTelegramInitData?: string | null;
}

export interface PostReminderApiRemindersPostRequest {
    reminderSchema: ReminderSchema;
    xTelegramInitData?: string | null;
}

export interface ProfileSelfApiProfileSelfGetRequest {
    xTelegramInitData?: string | null;
}

export interface ProfileSelfProfileSelfGetRequest {
    xTelegramInitData?: string | null;
}

export interface PutRoleUserUserIdRolePutRequest {
    userId: number;
    roleSchema: RoleSchema;
}

export interface PutTimezoneTimezonePutRequest {
    timezone: Timezone;
    xTelegramInitData?: string | null;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Create User
     */
    async createUserUserPostRaw(requestParameters: CreateUserUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        if (requestParameters['webUser'] == null) {
            throw new runtime.RequiredError(
                'webUser',
                'Required parameter "webUser" was null or undefined when calling createUserUserPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/user`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebUserToJSON(requestParameters['webUser']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create User
     */
    async createUserUserPost(requestParameters: CreateUserUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.createUserUserPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Reminder
     */
    async deleteReminderApiRemindersDeleteRaw(requestParameters: DeleteReminderApiRemindersDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const queryParameters: any = {};

        if (requestParameters['telegramId'] != null) {
            queryParameters['telegramId'] = requestParameters['telegramId'];
        }

        if (requestParameters['telegramId2'] != null) {
            queryParameters['telegram_id'] = requestParameters['telegramId2'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/api/reminders`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete Reminder
     */
    async deleteReminderApiRemindersDelete(requestParameters: DeleteReminderApiRemindersDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.deleteReminderApiRemindersDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Analytics
     */
    async getAnalyticsApiAnalyticsGetRaw(requestParameters: GetAnalyticsApiAnalyticsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AnalyticsPoint>>> {
        if (requestParameters['telegramId'] == null) {
            throw new runtime.RequiredError(
                'telegramId',
                'Required parameter "telegramId" was null or undefined when calling getAnalyticsApiAnalyticsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['telegramId'] != null) {
            queryParameters['telegramId'] = requestParameters['telegramId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/api/analytics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AnalyticsPointFromJSON));
    }

    /**
     * Get Analytics
     */
    async getAnalyticsApiAnalyticsGet(requestParameters: GetAnalyticsApiAnalyticsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AnalyticsPoint>> {
        const response = await this.getAnalyticsApiAnalyticsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Reminders
     */
    async getRemindersApiRemindersGetRaw(requestParameters: GetRemindersApiRemindersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseGetRemindersApiRemindersGet>> {
        const queryParameters: any = {};

        if (requestParameters['telegramId'] != null) {
            queryParameters['telegramId'] = requestParameters['telegramId'];
        }

        if (requestParameters['telegramId2'] != null) {
            queryParameters['telegram_id'] = requestParameters['telegramId2'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/api/reminders`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseGetRemindersApiRemindersGetFromJSON(jsonValue));
    }

    /**
     * Get Reminders
     */
    async getRemindersApiRemindersGet(requestParameters: GetRemindersApiRemindersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseGetRemindersApiRemindersGet> {
        const response = await this.getRemindersApiRemindersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Role
     */
    async getRoleUserUserIdRoleGetRaw(requestParameters: GetRoleUserUserIdRoleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleSchema>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getRoleUserUserIdRoleGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user/{user_id}/role`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleSchemaFromJSON(jsonValue));
    }

    /**
     * Get Role
     */
    async getRoleUserUserIdRoleGet(requestParameters: GetRoleUserUserIdRoleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleSchema> {
        const response = await this.getRoleUserUserIdRoleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Stats
     */
    async getStatsApiStatsGetRaw(requestParameters: GetStatsApiStatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DayStats>> {
        if (requestParameters['telegramId'] == null) {
            throw new runtime.RequiredError(
                'telegramId',
                'Required parameter "telegramId" was null or undefined when calling getStatsApiStatsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['telegramId'] != null) {
            queryParameters['telegramId'] = requestParameters['telegramId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/api/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DayStatsFromJSON(jsonValue));
    }

    /**
     * Get Stats
     */
    async getStatsApiStatsGet(requestParameters: GetStatsApiStatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DayStats | null | undefined > {
        const response = await this.getStatsApiStatsGetRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Get Timezone
     */
    async getTimezoneTimezoneGetRaw(requestParameters: GetTimezoneTimezoneGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/timezone`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Timezone
     */
    async getTimezoneTimezoneGet(requestParameters: GetTimezoneTimezoneGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.getTimezoneTimezoneGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Patch Reminder
     */
    async patchReminderApiRemindersPatchRaw(requestParameters: PatchReminderApiRemindersPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['reminderSchema'] == null) {
            throw new runtime.RequiredError(
                'reminderSchema',
                'Required parameter "reminderSchema" was null or undefined when calling patchReminderApiRemindersPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/api/reminders`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ReminderSchemaToJSON(requestParameters['reminderSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Patch Reminder
     */
    async patchReminderApiRemindersPatch(requestParameters: PatchReminderApiRemindersPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.patchReminderApiRemindersPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Post Reminder
     */
    async postReminderApiRemindersPostRaw(requestParameters: PostReminderApiRemindersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['reminderSchema'] == null) {
            throw new runtime.RequiredError(
                'reminderSchema',
                'Required parameter "reminderSchema" was null or undefined when calling postReminderApiRemindersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/api/reminders`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReminderSchemaToJSON(requestParameters['reminderSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Post Reminder
     */
    async postReminderApiRemindersPost(requestParameters: PostReminderApiRemindersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.postReminderApiRemindersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Profile Self
     */
    async profileSelfApiProfileSelfGetRaw(requestParameters: ProfileSelfApiProfileSelfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserContext>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/api/profile/self`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserContextFromJSON(jsonValue));
    }

    /**
     * Profile Self
     */
    async profileSelfApiProfileSelfGet(requestParameters: ProfileSelfApiProfileSelfGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserContext> {
        const response = await this.profileSelfApiProfileSelfGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Profile Self
     */
    async profileSelfProfileSelfGetRaw(requestParameters: ProfileSelfProfileSelfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserContext>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/profile/self`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserContextFromJSON(jsonValue));
    }

    /**
     * Profile Self
     */
    async profileSelfProfileSelfGet(requestParameters: ProfileSelfProfileSelfGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserContext> {
        const response = await this.profileSelfProfileSelfGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Put Role
     */
    async putRoleUserUserIdRolePutRaw(requestParameters: PutRoleUserUserIdRolePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleSchema>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling putRoleUserUserIdRolePut().'
            );
        }

        if (requestParameters['roleSchema'] == null) {
            throw new runtime.RequiredError(
                'roleSchema',
                'Required parameter "roleSchema" was null or undefined when calling putRoleUserUserIdRolePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/{user_id}/role`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RoleSchemaToJSON(requestParameters['roleSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleSchemaFromJSON(jsonValue));
    }

    /**
     * Put Role
     */
    async putRoleUserUserIdRolePut(requestParameters: PutRoleUserUserIdRolePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleSchema> {
        const response = await this.putRoleUserUserIdRolePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Put Timezone
     */
    async putTimezoneTimezonePutRaw(requestParameters: PutTimezoneTimezonePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        if (requestParameters['timezone'] == null) {
            throw new runtime.RequiredError(
                'timezone',
                'Required parameter "timezone" was null or undefined when calling putTimezoneTimezonePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTelegramInitData'] != null) {
            headerParameters['X-Telegram-Init-Data'] = String(requestParameters['xTelegramInitData']);
        }


        let urlPath = `/timezone`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TimezoneToJSON(requestParameters['timezone']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Put Timezone
     */
    async putTimezoneTimezonePut(requestParameters: PutTimezoneTimezonePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.putTimezoneTimezonePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
