/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Profile,
  Reminder,
  RemindersGet200Response,
  RemindersPost200Response,
  Status,
  Timezone,
} from '../models/index';
import {
    ProfileFromJSON,
    ProfileToJSON,
    ReminderFromJSON,
    ReminderToJSON,
    RemindersGet200ResponseFromJSON,
    RemindersGet200ResponseToJSON,
    RemindersPost200ResponseFromJSON,
    RemindersPost200ResponseToJSON,
    StatusFromJSON,
    StatusToJSON,
    TimezoneFromJSON,
    TimezoneToJSON,
} from '../models/index';

export interface ProfilesGetRequest {
    telegramId: number;
}

export interface ProfilesPostRequest {
    profile: Profile;
}

export interface RemindersGetRequest {
    telegramId: number;
    id?: number;
}

export interface RemindersPostRequest {
    reminder: Reminder;
}

export interface TimezonePostRequest {
    timezone: Timezone;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Health check
     */
    async healthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusFromJSON(jsonValue));
    }

    /**
     * Health check
     */
    async healthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status> {
        const response = await this.healthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get user profile
     */
    async profilesGetRaw(requestParameters: ProfilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        if (requestParameters['telegramId'] == null) {
            throw new runtime.RequiredError(
                'telegramId',
                'Required parameter "telegramId" was null or undefined when calling profilesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['telegramId'] != null) {
            queryParameters['telegram_id'] = requestParameters['telegramId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Get user profile
     */
    async profilesGet(requestParameters: ProfilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.profilesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save user profile
     */
    async profilesPostRaw(requestParameters: ProfilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>> {
        if (requestParameters['profile'] == null) {
            throw new runtime.RequiredError(
                'profile',
                'Required parameter "profile" was null or undefined when calling profilesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProfileToJSON(requestParameters['profile']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusFromJSON(jsonValue));
    }

    /**
     * Save user profile
     */
    async profilesPost(requestParameters: ProfilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status> {
        const response = await this.profilesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List or retrieve reminders
     */
    async remindersGetRaw(requestParameters: RemindersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemindersGet200Response>> {
        if (requestParameters['telegramId'] == null) {
            throw new runtime.RequiredError(
                'telegramId',
                'Required parameter "telegramId" was null or undefined when calling remindersGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['telegramId'] != null) {
            queryParameters['telegram_id'] = requestParameters['telegramId'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/reminders`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RemindersGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List or retrieve reminders
     */
    async remindersGet(requestParameters: RemindersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemindersGet200Response> {
        const response = await this.remindersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save reminder
     */
    async remindersPostRaw(requestParameters: RemindersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemindersPost200Response>> {
        if (requestParameters['reminder'] == null) {
            throw new runtime.RequiredError(
                'reminder',
                'Required parameter "reminder" was null or undefined when calling remindersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/reminders`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReminderToJSON(requestParameters['reminder']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RemindersPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Save reminder
     */
    async remindersPost(requestParameters: RemindersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemindersPost200Response> {
        const response = await this.remindersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save timezone
     */
    async timezonePostRaw(requestParameters: TimezonePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>> {
        if (requestParameters['timezone'] == null) {
            throw new runtime.RequiredError(
                'timezone',
                'Required parameter "timezone" was null or undefined when calling timezonePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/timezone`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimezoneToJSON(requestParameters['timezone']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusFromJSON(jsonValue));
    }

    /**
     * Save timezone
     */
    async timezonePost(requestParameters: TimezonePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status> {
        const response = await this.timezonePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
