/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsPoint
 */
export interface AnalyticsPoint {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsPoint
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsPoint
     */
    sugar: number;
}

/**
 * Check if a given object implements the AnalyticsPoint interface.
 */
export function instanceOfAnalyticsPoint(value: object): value is AnalyticsPoint {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('sugar' in value) || value['sugar'] === undefined) return false;
    return true;
}

export function AnalyticsPointFromJSON(json: any): AnalyticsPoint {
    return AnalyticsPointFromJSONTyped(json, false);
}

export function AnalyticsPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'sugar': json['sugar'],
    };
}

export function AnalyticsPointToJSON(json: any): AnalyticsPoint {
    return AnalyticsPointToJSONTyped(json, false);
}

export function AnalyticsPointToJSONTyped(value?: AnalyticsPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'sugar': value['sugar'],
    };
}

