/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRemindersPost200Response
 */
export interface ApiRemindersPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiRemindersPost200Response
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiRemindersPost200Response
     */
    id?: number;
}

/**
 * Check if a given object implements the ApiRemindersPost200Response interface.
 */
export function instanceOfApiRemindersPost200Response(value: object): value is ApiRemindersPost200Response {
    return true;
}

export function ApiRemindersPost200ResponseFromJSON(json: any): ApiRemindersPost200Response {
    return ApiRemindersPost200ResponseFromJSONTyped(json, false);
}

export function ApiRemindersPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRemindersPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ApiRemindersPost200ResponseToJSON(json: any): ApiRemindersPost200Response {
    return ApiRemindersPost200ResponseToJSONTyped(json, false);
}

export function ApiRemindersPost200ResponseToJSONTyped(value?: ApiRemindersPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'id': value['id'],
    };
}

