/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DayStats
 */
export interface DayStats {
    /**
     * 
     * @type {number}
     * @memberof DayStats
     */
    sugar: number;
    /**
     * 
     * @type {number}
     * @memberof DayStats
     */
    breadUnits: number;
    /**
     * 
     * @type {number}
     * @memberof DayStats
     */
    insulin: number;
}

/**
 * Check if a given object implements the DayStats interface.
 */
export function instanceOfDayStats(value: object): value is DayStats {
    if (!('sugar' in value) || value['sugar'] === undefined) return false;
    if (!('breadUnits' in value) || value['breadUnits'] === undefined) return false;
    if (!('insulin' in value) || value['insulin'] === undefined) return false;
    return true;
}

export function DayStatsFromJSON(json: any): DayStats {
    return DayStatsFromJSONTyped(json, false);
}

export function DayStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayStats {
    if (json == null) {
        return json;
    }
    return {
        
        'sugar': json['sugar'],
        'breadUnits': json['breadUnits'],
        'insulin': json['insulin'],
    };
}

export function DayStatsToJSON(json: any): DayStats {
    return DayStatsToJSONTyped(json, false);
}

export function DayStatsToJSONTyped(value?: DayStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sugar': value['sugar'],
        'breadUnits': value['breadUnits'],
        'insulin': value['insulin'],
    };
}

