/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventPayload
 */
export interface EventPayload {
    /**
     * 
     * @type {string}
     * @memberof EventPayload
     */
    event: string;
    /**
     * 
     * @type {number}
     * @memberof EventPayload
     */
    step?: number | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EventPayload
     */
    meta?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the EventPayload interface.
 */
export function instanceOfEventPayload(value: object): value is EventPayload {
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function EventPayloadFromJSON(json: any): EventPayload {
    return EventPayloadFromJSONTyped(json, false);
}

export function EventPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['event'],
        'step': json['step'] == null ? undefined : json['step'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function EventPayloadToJSON(json: any): EventPayload {
    return EventPayloadToJSONTyped(json, false);
}

export function EventPayloadToJSONTyped(value?: EventPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': value['event'],
        'step': value['step'],
        'meta': value['meta'],
    };
}

