/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for user history records.
 * @export
 * @interface HistoryRecordSchemaOutput
 */
export interface HistoryRecordSchemaOutput {
    /**
     * 
     * @type {string}
     * @memberof HistoryRecordSchemaOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryRecordSchemaOutput
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryRecordSchemaOutput
     */
    time: string;
    /**
     * 
     * @type {number}
     * @memberof HistoryRecordSchemaOutput
     */
    sugar?: number | null;
    /**
     * 
     * @type {number}
     * @memberof HistoryRecordSchemaOutput
     */
    carbs?: number | null;
    /**
     * 
     * @type {number}
     * @memberof HistoryRecordSchemaOutput
     */
    breadUnits?: number | null;
    /**
     * 
     * @type {number}
     * @memberof HistoryRecordSchemaOutput
     */
    insulin?: number | null;
    /**
     * 
     * @type {string}
     * @memberof HistoryRecordSchemaOutput
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HistoryRecordSchemaOutput
     */
    type: HistoryRecordSchemaOutputTypeEnum;
}


/**
 * @export
 */
export const HistoryRecordSchemaOutputTypeEnum = {
    Measurement: 'measurement',
    Meal: 'meal',
    Insulin: 'insulin'
} as const;
export type HistoryRecordSchemaOutputTypeEnum = typeof HistoryRecordSchemaOutputTypeEnum[keyof typeof HistoryRecordSchemaOutputTypeEnum];


/**
 * Check if a given object implements the HistoryRecordSchemaOutput interface.
 */
export function instanceOfHistoryRecordSchemaOutput(value: object): value is HistoryRecordSchemaOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function HistoryRecordSchemaOutputFromJSON(json: any): HistoryRecordSchemaOutput {
    return HistoryRecordSchemaOutputFromJSONTyped(json, false);
}

export function HistoryRecordSchemaOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryRecordSchemaOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': json['date'],
        'time': json['time'],
        'sugar': json['sugar'] == null ? undefined : json['sugar'],
        'carbs': json['carbs'] == null ? undefined : json['carbs'],
        'breadUnits': json['breadUnits'] == null ? undefined : json['breadUnits'],
        'insulin': json['insulin'] == null ? undefined : json['insulin'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'type': json['type'],
    };
}

export function HistoryRecordSchemaOutputToJSON(json: any): HistoryRecordSchemaOutput {
    return HistoryRecordSchemaOutputToJSONTyped(json, false);
}

export function HistoryRecordSchemaOutputToJSONTyped(value?: HistoryRecordSchemaOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': value['date'],
        'time': value['time'],
        'sugar': value['sugar'],
        'carbs': value['carbs'],
        'breadUnits': value['breadUnits'],
        'insulin': value['insulin'],
        'notes': value['notes'],
        'type': value['type'],
    };
}

