/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnboardingStatusResponse
 */
export interface OnboardingStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof OnboardingStatusResponse
     */
    completed: boolean;
    /**
     * 
     * @type {string}
     * @memberof OnboardingStatusResponse
     */
    step: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof OnboardingStatusResponse
     */
    missing: Array<string>;
}

/**
 * Check if a given object implements the OnboardingStatusResponse interface.
 */
export function instanceOfOnboardingStatusResponse(value: object): value is OnboardingStatusResponse {
    if (!('completed' in value) || value['completed'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    if (!('missing' in value) || value['missing'] === undefined) return false;
    return true;
}

export function OnboardingStatusResponseFromJSON(json: any): OnboardingStatusResponse {
    return OnboardingStatusResponseFromJSONTyped(json, false);
}

export function OnboardingStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'completed': json['completed'],
        'step': json['step'],
        'missing': json['missing'],
    };
}

export function OnboardingStatusResponseToJSON(json: any): OnboardingStatusResponse {
    return OnboardingStatusResponseToJSONTyped(json, false);
}

export function OnboardingStatusResponseToJSONTyped(value?: OnboardingStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
        'step': value['step'],
        'missing': value['missing'],
    };
}

