/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileSchema
 */
export interface ProfileSchema {
    /**
     * 
     * @type {number}
     * @memberof ProfileSchema
     */
    telegramId: number;
    /**
     * 
     * @type {number}
     * @memberof ProfileSchema
     */
    icr?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProfileSchema
     */
    cf?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProfileSchema
     */
    target: number;
    /**
     * Alias `targetLow` accepted on input.
     * @type {number}
     * @memberof ProfileSchema
     */
    low: number;
    /**
     * Alias `targetHigh` accepted on input.
     * @type {number}
     * @memberof ProfileSchema
     */
    high: number;
    /**
     * 
     * @type {string}
     * @memberof ProfileSchema
     */
    quietStart?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileSchema
     */
    quietEnd?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileSchema
     */
    sosContact?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileSchema
     */
    therapyType?: ProfileSchemaTherapyTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileSchema
     */
    sosAlertsEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProfileSchema
     */
    timezone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileSchema
     */
    timezoneAuto?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProfileSchema
     */
    orgId?: number | null;
}


/**
 * @export
 */
export const ProfileSchemaTherapyTypeEnum = {
    Insulin: 'insulin',
    Tablets: 'tablets',
    None: 'none',
    Mixed: 'mixed'
} as const;
export type ProfileSchemaTherapyTypeEnum = typeof ProfileSchemaTherapyTypeEnum[keyof typeof ProfileSchemaTherapyTypeEnum];


/**
 * Check if a given object implements the ProfileSchema interface.
 */
export function instanceOfProfileSchema(value: object): value is ProfileSchema {
    if (!('telegramId' in value) || value['telegramId'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('low' in value) || value['low'] === undefined) return false;
    if (!('high' in value) || value['high'] === undefined) return false;
    return true;
}

export function ProfileSchemaFromJSON(json: any): ProfileSchema {
    return ProfileSchemaFromJSONTyped(json, false);
}

export function ProfileSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'telegramId': json['telegramId'],
        'icr': json['icr'] == null ? undefined : json['icr'],
        'cf': json['cf'] == null ? undefined : json['cf'],
        'target': json['target'],
        'low': json['low'],
        'high': json['high'],
        'quietStart': json['quietStart'] == null ? undefined : json['quietStart'],
        'quietEnd': json['quietEnd'] == null ? undefined : json['quietEnd'],
        'sosContact': json['sosContact'] == null ? undefined : json['sosContact'],
        'therapyType': json['therapyType'] == null ? undefined : json['therapyType'],
        'sosAlertsEnabled': json['sosAlertsEnabled'] == null ? undefined : json['sosAlertsEnabled'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'timezoneAuto': json['timezoneAuto'] == null ? undefined : json['timezoneAuto'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
    };
}

export function ProfileSchemaToJSON(json: any): ProfileSchema {
    return ProfileSchemaToJSONTyped(json, false);
}

export function ProfileSchemaToJSONTyped(value?: ProfileSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'telegramId': value['telegramId'],
        'icr': value['icr'],
        'cf': value['cf'],
        'target': value['target'],
        'low': value['low'],
        'high': value['high'],
        'quietStart': value['quietStart'],
        'quietEnd': value['quietEnd'],
        'sosContact': value['sosContact'],
        'therapyType': value['therapyType'],
        'sosAlertsEnabled': value['sosAlertsEnabled'],
        'timezone': value['timezone'],
        'timezoneAuto': value['timezoneAuto'],
        'orgId': value['orgId'],
    };
}

