/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfilePatchRequest
 */
export interface ProfilePatchRequest {
    /**
     * 
     * @type {string}
     * @memberof ProfilePatchRequest
     */
    timezone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProfilePatchRequest
     */
    timezoneAuto?: boolean;
}

/**
 * Check if a given object implements the ProfilePatchRequest interface.
 */
export function instanceOfProfilePatchRequest(value: object): value is ProfilePatchRequest {
    return true;
}

export function ProfilePatchRequestFromJSON(json: any): ProfilePatchRequest {
    return ProfilePatchRequestFromJSONTyped(json, false);
}

export function ProfilePatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilePatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'timezoneAuto': json['timezoneAuto'] == null ? undefined : json['timezoneAuto'],
    };
}

export function ProfilePatchRequestToJSON(json: any): ProfilePatchRequest {
    return ProfilePatchRequestToJSONTyped(json, false);
}

export function ProfilePatchRequestToJSONTyped(value?: ProfilePatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timezone': value['timezone'],
        'timezoneAuto': value['timezoneAuto'],
    };
}

