/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileSettingsIn
 */
export interface ProfileSettingsIn {
    /**
     * 
     * @type {string}
     * @memberof ProfileSettingsIn
     */
    timezone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileSettingsIn
     */
    timezoneAuto?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProfileSettingsIn
     */
    dia?: number;
    /**
     * 
     * @type {number}
     * @memberof ProfileSettingsIn
     */
    roundStep?: number;
    /**
     * 
     * @type {string}
     * @memberof ProfileSettingsIn
     */
    carbUnits?: ProfileSettingsInCarbUnitsEnum;
}


/**
 * @export
 */
export const ProfileSettingsInCarbUnitsEnum = {
    G: 'g',
    Xe: 'xe'
} as const;
export type ProfileSettingsInCarbUnitsEnum = typeof ProfileSettingsInCarbUnitsEnum[keyof typeof ProfileSettingsInCarbUnitsEnum];


/**
 * Check if a given object implements the ProfileSettingsIn interface.
 */
export function instanceOfProfileSettingsIn(value: object): value is ProfileSettingsIn {
    return true;
}

export function ProfileSettingsInFromJSON(json: any): ProfileSettingsIn {
    return ProfileSettingsInFromJSONTyped(json, false);
}

export function ProfileSettingsInFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileSettingsIn {
    if (json == null) {
        return json;
    }
    return {
        
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'timezoneAuto': json['timezoneAuto'] == null ? undefined : json['timezoneAuto'],
        'dia': json['dia'] == null ? undefined : json['dia'],
        'roundStep': json['roundStep'] == null ? undefined : json['roundStep'],
        'carbUnits': json['carbUnits'] == null ? undefined : json['carbUnits'],
    };
}

export function ProfileSettingsInToJSON(json: any): ProfileSettingsIn {
    return ProfileSettingsInToJSONTyped(json, false);
}

export function ProfileSettingsInToJSONTyped(value?: ProfileSettingsIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timezone': value['timezone'],
        'timezoneAuto': value['timezoneAuto'],
        'dia': value['dia'],
        'roundStep': value['roundStep'],
        'carbUnits': value['carbUnits'],
    };
}

