/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReminderType = {
    Sugar: 'sugar',
    InsulinShort: 'insulin_short',
    InsulinLong: 'insulin_long',
    AfterMeal: 'after_meal',
    Meal: 'meal',
    SensorChange: 'sensor_change',
    InjectionSite: 'injection_site',
    Custom: 'custom'
} as const;
export type ReminderType = typeof ReminderType[keyof typeof ReminderType];


export function instanceOfReminderType(value: any): boolean {
    for (const key in ReminderType) {
        if (Object.prototype.hasOwnProperty.call(ReminderType, key)) {
            if (ReminderType[key as keyof typeof ReminderType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReminderTypeFromJSON(json: any): ReminderType {
    return ReminderTypeFromJSONTyped(json, false);
}

export function ReminderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReminderType {
    return json as ReminderType;
}

export function ReminderTypeToJSON(value?: ReminderType | null): any {
    return value as any;
}

export function ReminderTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ReminderType {
    return value as ReminderType;
}

