/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Reminder
 */
export interface Reminder {
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    telegramId: number;
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    time?: string;
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    intervalHours?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Reminder
     */
    isEnabled?: boolean;
}

/**
 * Check if a given object implements the Reminder interface.
 */
export function instanceOfReminder(value: object): value is Reminder {
    if (!('telegramId' in value) || value['telegramId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ReminderFromJSON(json: any): Reminder {
    return ReminderFromJSONTyped(json, false);
}

export function ReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reminder {
    if (json == null) {
        return json;
    }
    return {
        
        'telegramId': json['telegram_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'],
        'time': json['time'] == null ? undefined : json['time'],
        'intervalHours': json['interval_hours'] == null ? undefined : json['interval_hours'],
        'isEnabled': json['is_enabled'] == null ? undefined : json['is_enabled'],
    };
}

export function ReminderToJSON(json: any): Reminder {
    return ReminderToJSONTyped(json, false);
}

export function ReminderToJSONTyped(value?: Reminder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'telegram_id': value['telegramId'],
        'id': value['id'],
        'type': value['type'],
        'time': value['time'],
        'interval_hours': value['intervalHours'],
        'is_enabled': value['isEnabled'],
    };
}

