/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseApiRemindersRemindersGet
 */
export interface ResponseApiRemindersRemindersGet {
}

/**
 * Check if a given object implements the ResponseApiRemindersRemindersGet interface.
 */
export function instanceOfResponseApiRemindersRemindersGet(value: object): value is ResponseApiRemindersRemindersGet {
    return true;
}

export function ResponseApiRemindersRemindersGetFromJSON(json: any): ResponseApiRemindersRemindersGet {
    return ResponseApiRemindersRemindersGetFromJSONTyped(json, false);
}

export function ResponseApiRemindersRemindersGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseApiRemindersRemindersGet {
    return json;
}

export function ResponseApiRemindersRemindersGetToJSON(json: any): ResponseApiRemindersRemindersGet {
    return ResponseApiRemindersRemindersGetToJSONTyped(json, false);
}

export function ResponseApiRemindersRemindersGetToJSONTyped(value?: ResponseApiRemindersRemindersGet | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

