/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseGetRemindersApiRemindersGet
 */
export interface ResponseGetRemindersApiRemindersGet {
}

/**
 * Check if a given object implements the ResponseGetRemindersApiRemindersGet interface.
 */
export function instanceOfResponseGetRemindersApiRemindersGet(value: object): value is ResponseGetRemindersApiRemindersGet {
    return true;
}

export function ResponseGetRemindersApiRemindersGetFromJSON(json: any): ResponseGetRemindersApiRemindersGet {
    return ResponseGetRemindersApiRemindersGetFromJSONTyped(json, false);
}

export function ResponseGetRemindersApiRemindersGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseGetRemindersApiRemindersGet {
    return json;
}

export function ResponseGetRemindersApiRemindersGetToJSON(json: any): ResponseGetRemindersApiRemindersGet {
    return ResponseGetRemindersApiRemindersGetToJSONTyped(json, false);
}

export function ResponseGetRemindersApiRemindersGetToJSONTyped(value?: ResponseGetRemindersApiRemindersGet | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

