/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleSchema
 */
export interface RoleSchema {
    /**
     * 
     * @type {string}
     * @memberof RoleSchema
     */
    role: string;
}

/**
 * Check if a given object implements the RoleSchema interface.
 */
export function instanceOfRoleSchema(value: object): value is RoleSchema {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function RoleSchemaFromJSON(json: any): RoleSchema {
    return RoleSchemaFromJSONTyped(json, false);
}

export function RoleSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
    };
}

export function RoleSchemaToJSON(json: any): RoleSchema {
    return RoleSchemaToJSONTyped(json, false);
}

export function RoleSchemaToJSONTyped(value?: RoleSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
    };
}

