/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Telegram user data supplied via WebApp init data.
 * @export
 * @interface UserContext
 */
export interface UserContext {
    /**
     * 
     * @type {number}
     * @memberof UserContext
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserContext
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContext
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContext
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserContext
     */
    languageCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserContext
     */
    isPremium?: boolean;
}

/**
 * Check if a given object implements the UserContext interface.
 */
export function instanceOfUserContext(value: object): value is UserContext {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserContextFromJSON(json: any): UserContext {
    return UserContextFromJSONTyped(json, false);
}

export function UserContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserContext {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'username': json['username'] == null ? undefined : json['username'],
        'languageCode': json['language_code'] == null ? undefined : json['language_code'],
        'isPremium': json['is_premium'] == null ? undefined : json['is_premium'],
    };
}

export function UserContextToJSON(json: any): UserContext {
    return UserContextToJSONTyped(json, false);
}

export function UserContextToJSONTyped(value?: UserContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'username': value['username'],
        'language_code': value['languageCode'],
        'is_premium': value['isPremium'],
    };
}

