/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebUser
 */
export interface WebUser {
    /**
     * 
     * @type {number}
     * @memberof WebUser
     */
    telegramId: number;
}

/**
 * Check if a given object implements the WebUser interface.
 */
export function instanceOfWebUser(value: object): value is WebUser {
    if (!('telegramId' in value) || value['telegramId'] === undefined) return false;
    return true;
}

export function WebUserFromJSON(json: any): WebUser {
    return WebUserFromJSONTyped(json, false);
}

export function WebUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebUser {
    if (json == null) {
        return json;
    }
    return {
        
        'telegramId': json['telegram_id'],
    };
}

export function WebUserToJSON(json: any): WebUser {
    return WebUserToJSONTyped(json, false);
}

export function WebUserToJSONTyped(value?: WebUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'telegram_id': value['telegramId'],
    };
}

