/* tslint:disable */
/* eslint-disable */
/**
 * Diabetes Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AuthRequest
 */
export interface AuthRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof AuthRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    'token': string;
    /**
     * 
     * @type {number}
     * @memberof AuthResponse
     */
    'user_id': number;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    'role': string;
}
/**
 * @type EntriesGet200Response
 * @export
 */
export type EntriesGet200Response = Array<Entry> | Entry;

/**
 * 
 * @export
 * @interface EntriesPost200Response
 */
export interface EntriesPost200Response {
    /**
     * 
     * @type {string}
     * @memberof EntriesPost200Response
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof EntriesPost200Response
     */
    'id'?: number;
}
/**
 * 
 * @export
 * @interface Entry
 */
export interface Entry {
    /**
     * 
     * @type {number}
     * @memberof Entry
     */
    'telegram_id': number;
    /**
     * 
     * @type {number}
     * @memberof Entry
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    'event_time': string;
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    'photo_path'?: string;
    /**
     * 
     * @type {number}
     * @memberof Entry
     */
    'carbs_g'?: number;
    /**
     * 
     * @type {number}
     * @memberof Entry
     */
    'xe'?: number;
    /**
     * 
     * @type {number}
     * @memberof Entry
     */
    'sugar_before'?: number;
    /**
     * 
     * @type {number}
     * @memberof Entry
     */
    'dose'?: number;
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    'gpt_summary'?: string;
}
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    'telegram_id': number;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    'icr': number;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    'cf': number;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    'target': number;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    'low': number;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    'high': number;
}
/**
 * 
 * @export
 * @interface Reminder
 */
export interface Reminder {
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    'telegram_id': number;
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'time'?: string;
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    'interval_hours'?: number;
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    'minutes_after'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Reminder
     */
    'is_enabled'?: boolean;
}
/**
 * @type RemindersGet200Response
 * @export
 */
export type RemindersGet200Response = Array<Reminder> | Reminder;

/**
 * 
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * 
     * @type {string}
     * @memberof Status
     */
    'status': string;
}
/**
 * 
 * @export
 * @interface Timezone
 */
export interface Timezone {
    /**
     * 
     * @type {number}
     * @memberof Timezone
     */
    'telegram_id': number;
    /**
     * 
     * @type {string}
     * @memberof Timezone
     */
    'tz': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Authenticate user
         * @param {AuthRequest} authRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPost: async (authRequest: AuthRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authRequest' is not null or undefined
            assertParamExists('authPost', 'authRequest', authRequest)
            const localVarPath = `/auth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List or retrieve entries
         * @param {number} telegramId 
         * @param {number} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        entriesGet: async (telegramId: number, id?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'telegramId' is not null or undefined
            assertParamExists('entriesGet', 'telegramId', telegramId)
            const localVarPath = `/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (telegramId !== undefined) {
                localVarQueryParameter['telegram_id'] = telegramId;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Save entry
         * @param {Entry} entry 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        entriesPost: async (entry: Entry, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entry' is not null or undefined
            assertParamExists('entriesPost', 'entry', entry)
            const localVarPath = `/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(entry, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get user profile
         * @param {number} telegramId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesGet: async (telegramId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'telegramId' is not null or undefined
            assertParamExists('profilesGet', 'telegramId', telegramId)
            const localVarPath = `/profiles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (telegramId !== undefined) {
                localVarQueryParameter['telegram_id'] = telegramId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Save user profile
         * @param {Profile} profile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesPost: async (profile: Profile, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'profile' is not null or undefined
            assertParamExists('profilesPost', 'profile', profile)
            const localVarPath = `/profiles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profile, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List or retrieve reminders
         * @param {number} telegramId 
         * @param {number} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remindersGet: async (telegramId: number, id?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'telegramId' is not null or undefined
            assertParamExists('remindersGet', 'telegramId', telegramId)
            const localVarPath = `/reminders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (telegramId !== undefined) {
                localVarQueryParameter['telegram_id'] = telegramId;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Save reminder
         * @param {Reminder} reminder 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remindersPost: async (reminder: Reminder, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reminder' is not null or undefined
            assertParamExists('remindersPost', 'reminder', reminder)
            const localVarPath = `/reminders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reminder, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Generate report
         * @param {number} telegramId 
         * @param {number} [periodDays] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsGet: async (telegramId: number, periodDays?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'telegramId' is not null or undefined
            assertParamExists('reportsGet', 'telegramId', telegramId)
            const localVarPath = `/reports`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (telegramId !== undefined) {
                localVarQueryParameter['telegram_id'] = telegramId;
            }

            if (periodDays !== undefined) {
                localVarQueryParameter['period_days'] = periodDays;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Authenticate user
         * @param {AuthRequest} authRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authPost(authRequest: AuthRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authPost(authRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List or retrieve entries
         * @param {number} telegramId 
         * @param {number} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async entriesGet(telegramId: number, id?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntriesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.entriesGet(telegramId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.entriesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Save entry
         * @param {Entry} entry 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async entriesPost(entry: Entry, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntriesPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.entriesPost(entry, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.entriesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get user profile
         * @param {number} telegramId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profilesGet(telegramId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Profile>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profilesGet(telegramId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.profilesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Save user profile
         * @param {Profile} profile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profilesPost(profile: Profile, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Status>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profilesPost(profile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.profilesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List or retrieve reminders
         * @param {number} telegramId 
         * @param {number} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remindersGet(telegramId: number, id?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RemindersGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remindersGet(telegramId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.remindersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Save reminder
         * @param {Reminder} reminder 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remindersPost(reminder: Reminder, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntriesPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remindersPost(reminder, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.remindersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Generate report
         * @param {number} telegramId 
         * @param {number} [periodDays] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reportsGet(telegramId: number, periodDays?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reportsGet(telegramId, periodDays, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.reportsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Authenticate user
         * @param {AuthRequest} authRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPost(authRequest: AuthRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthResponse> {
            return localVarFp.authPost(authRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List or retrieve entries
         * @param {number} telegramId 
         * @param {number} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        entriesGet(telegramId: number, id?: number, options?: RawAxiosRequestConfig): AxiosPromise<EntriesGet200Response> {
            return localVarFp.entriesGet(telegramId, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Save entry
         * @param {Entry} entry 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        entriesPost(entry: Entry, options?: RawAxiosRequestConfig): AxiosPromise<EntriesPost200Response> {
            return localVarFp.entriesPost(entry, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get user profile
         * @param {number} telegramId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesGet(telegramId: number, options?: RawAxiosRequestConfig): AxiosPromise<Profile> {
            return localVarFp.profilesGet(telegramId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Save user profile
         * @param {Profile} profile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesPost(profile: Profile, options?: RawAxiosRequestConfig): AxiosPromise<Status> {
            return localVarFp.profilesPost(profile, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List or retrieve reminders
         * @param {number} telegramId 
         * @param {number} [id] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remindersGet(telegramId: number, id?: number, options?: RawAxiosRequestConfig): AxiosPromise<RemindersGet200Response> {
            return localVarFp.remindersGet(telegramId, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Save reminder
         * @param {Reminder} reminder 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remindersPost(reminder: Reminder, options?: RawAxiosRequestConfig): AxiosPromise<EntriesPost200Response> {
            return localVarFp.remindersPost(reminder, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Generate report
         * @param {number} telegramId 
         * @param {number} [periodDays] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsGet(telegramId: number, periodDays?: number, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.reportsGet(telegramId, periodDays, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Authenticate user
     * @param {AuthRequest} authRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authPost(authRequest: AuthRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authPost(authRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List or retrieve entries
     * @param {number} telegramId 
     * @param {number} [id] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public entriesGet(telegramId: number, id?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).entriesGet(telegramId, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Save entry
     * @param {Entry} entry 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public entriesPost(entry: Entry, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).entriesPost(entry, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get user profile
     * @param {number} telegramId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public profilesGet(telegramId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).profilesGet(telegramId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Save user profile
     * @param {Profile} profile 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public profilesPost(profile: Profile, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).profilesPost(profile, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List or retrieve reminders
     * @param {number} telegramId 
     * @param {number} [id] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public remindersGet(telegramId: number, id?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).remindersGet(telegramId, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Save reminder
     * @param {Reminder} reminder 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public remindersPost(reminder: Reminder, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).remindersPost(reminder, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Generate report
     * @param {number} telegramId 
     * @param {number} [periodDays] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public reportsGet(telegramId: number, periodDays?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).reportsGet(telegramId, periodDays, options).then((request) => request(this.axios, this.basePath));
    }
}



