from typing import Any

class ClientSession:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> "ClientSession": ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> None: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
