version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  clinic-panel:
    image: node:18
    working_dir: /workspace/services/clinic-panel
    volumes:
      - ../..:/workspace
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm run dev"]

  worker:
    image: python:3.11
    working_dir: /workspace/services/worker
    volumes:
      - ../..:/workspace
    command: ["sh", "-c", "pip install -r requirements.txt && python main.py"]
