version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    env_file: [ ../env/.env.example ]
    ports:
      - "8000:8000"
    command: >-
      uvicorn services.api.app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: diabetes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

