version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    restart: unless-stopped
