# coding: utf-8

# flake8: noqa

"""
Diabetes Assistant API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AnalyticsPoint",
    "DayStats",
    "HTTPValidationError",
    "HistoryRecordSchemaInput",
    "HistoryRecordSchemaOutput",
    "ProfileSchema",
    "ReminderSchema",
    "ResponseApiRemindersRemindersGet",
    "Timezone",
    "UserContext",
    "ValidationError",
    "ValidationErrorLocInner",
    "WebUser",
]

# import apis into sdk package
from diabetes_sdk.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from diabetes_sdk.api_response import ApiResponse as ApiResponse
from diabetes_sdk.api_client import ApiClient as ApiClient
from diabetes_sdk.configuration import Configuration as Configuration
from diabetes_sdk.exceptions import OpenApiException as OpenApiException
from diabetes_sdk.exceptions import ApiTypeError as ApiTypeError
from diabetes_sdk.exceptions import ApiValueError as ApiValueError
from diabetes_sdk.exceptions import ApiKeyError as ApiKeyError
from diabetes_sdk.exceptions import ApiAttributeError as ApiAttributeError
from diabetes_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from diabetes_sdk.models.analytics_point import AnalyticsPoint as AnalyticsPoint
from diabetes_sdk.models.day_stats import DayStats as DayStats
from diabetes_sdk.models.http_validation_error import (
    HTTPValidationError as HTTPValidationError,
)
from diabetes_sdk.models.history_record_schema_input import (
    HistoryRecordSchemaInput as HistoryRecordSchemaInput,
)
from diabetes_sdk.models.history_record_schema_output import (
    HistoryRecordSchemaOutput as HistoryRecordSchemaOutput,
)
from diabetes_sdk.models.profile_schema import ProfileSchema as ProfileSchema
from diabetes_sdk.models.reminder_schema import ReminderSchema as ReminderSchema
from diabetes_sdk.models.response_api_reminders_reminders_get import (
    ResponseApiRemindersRemindersGet as ResponseApiRemindersRemindersGet,
)
from diabetes_sdk.models.timezone import Timezone as Timezone
from diabetes_sdk.models.user_context import UserContext as UserContext
from diabetes_sdk.models.validation_error import ValidationError as ValidationError
from diabetes_sdk.models.validation_error_loc_inner import (
    ValidationErrorLocInner as ValidationErrorLocInner,
)
from diabetes_sdk.models.web_user import WebUser as WebUser
