# coding: utf-8

# flake8: noqa

"""
    Diabetes Assistant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiRemindersGet200Response",
    "ApiRemindersPost200Response",
    "Profile",
    "Reminder",
    "Status",
    "Timezone",
]

# import apis into sdk package
from diabetes_sdk.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from diabetes_sdk.api_response import ApiResponse as ApiResponse
from diabetes_sdk.api_client import ApiClient as ApiClient
from diabetes_sdk.configuration import Configuration as Configuration
from diabetes_sdk.exceptions import OpenApiException as OpenApiException
from diabetes_sdk.exceptions import ApiTypeError as ApiTypeError
from diabetes_sdk.exceptions import ApiValueError as ApiValueError
from diabetes_sdk.exceptions import ApiKeyError as ApiKeyError
from diabetes_sdk.exceptions import ApiAttributeError as ApiAttributeError
from diabetes_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from diabetes_sdk.models.api_reminders_get200_response import ApiRemindersGet200Response as ApiRemindersGet200Response
from diabetes_sdk.models.api_reminders_post200_response import ApiRemindersPost200Response as ApiRemindersPost200Response
from diabetes_sdk.models.profile import Profile as Profile
from diabetes_sdk.models.reminder import Reminder as Reminder
from diabetes_sdk.models.status import Status as Status
from diabetes_sdk.models.timezone import Timezone as Timezone
