# coding: utf-8

"""
Diabetes Assistant API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.api.history_api import HistoryApi


class TestHistoryApi(unittest.TestCase):
    """HistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HistoryApi()

    def tearDown(self) -> None:
        pass

    def test_history_get(self) -> None:
        """Test case for history_get

        Get History
        """
        pass

    def test_history_id_delete(self) -> None:
        """Test case for history_id_delete

        Delete History
        """
        pass

    def test_history_post(self) -> None:
        """Test case for history_post

        Post History
        """
        pass


if __name__ == "__main__":
    unittest.main()
