# coding: utf-8

"""
    Diabetes Assistant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.models.api_reminders_post200_response import ApiRemindersPost200Response

class TestApiRemindersPost200Response(unittest.TestCase):
    """ApiRemindersPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiRemindersPost200Response:
        """Test ApiRemindersPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiRemindersPost200Response`
        """
        model = ApiRemindersPost200Response()
        if include_optional:
            return ApiRemindersPost200Response(
                status = '',
                id = 56
            )
        else:
            return ApiRemindersPost200Response(
        )
        """

    def testApiRemindersPost200Response(self):
        """Test ApiRemindersPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
