# coding: utf-8

"""
    Diabetes Assistant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_user_user_post(self) -> None:
        """Test case for create_user_user_post

        Create User
        """
        pass

    def test_get_analytics_analytics_get(self) -> None:
        """Test case for get_analytics_analytics_get

        Get Analytics
        """
        pass

    def test_get_role_user_user_id_role_get(self) -> None:
        """Test case for get_role_user_user_id_role_get

        Get Role
        """
        pass

    def test_get_stats_stats_get(self) -> None:
        """Test case for get_stats_stats_get

        Get Stats
        """
        pass

    def test_get_timezone_timezone_get(self) -> None:
        """Test case for get_timezone_timezone_get

        Get Timezone
        """
        pass

    def test_health_get(self) -> None:
        """Test case for health_get

        Health
        """
        pass

    def test_profile_self_profile_self_get(self) -> None:
        """Test case for profile_self_profile_self_get

        Profile Self
        """
        pass

    def test_put_role_user_user_id_role_put(self) -> None:
        """Test case for put_role_user_user_id_role_put

        Put Role
        """
        pass

    def test_put_timezone_timezone_put(self) -> None:
        """Test case for put_timezone_timezone_put

        Put Timezone
        """
        pass


if __name__ == '__main__':
    unittest.main()
