# coding: utf-8

"""
Diabetes Assistant API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.api.profiles_api import ProfilesApi


class TestProfilesApi(unittest.TestCase):
    """ProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_profiles_get_profiles_get(self) -> None:
        """Test case for profiles_get_profiles_get

        Profiles Get
        """
        pass

    def test_profiles_post_profiles_post(self) -> None:
        """Test case for profiles_post_profiles_post

        Profiles Post
        """
        pass


if __name__ == "__main__":
    unittest.main()
