# coding: utf-8

"""
    Diabetes Assistant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.models.day_stats import DayStats

class TestDayStats(unittest.TestCase):
    """DayStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DayStats:
        """Test DayStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DayStats`
        """
        model = DayStats()
        if include_optional:
            return DayStats(
                sugar = 1.337,
                bread_units = 1.337,
                insulin = 1.337
            )
        else:
            return DayStats(
                sugar = 1.337,
                bread_units = 1.337,
                insulin = 1.337,
        )
        """

    def testDayStats(self):
        """Test DayStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
