# coding: utf-8

"""
    Diabetes Assistant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_sdk.diabetes_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_auth_post(self) -> None:
        """Test case for auth_post

        Authenticate user
        """
        pass

    def test_entries_get(self) -> None:
        """Test case for entries_get

        List or retrieve entries
        """
        pass

    def test_entries_post(self) -> None:
        """Test case for entries_post

        Save entry
        """
        pass

    def test_profiles_get(self) -> None:
        """Test case for profiles_get

        Get user profile
        """
        pass

    def test_profiles_post(self) -> None:
        """Test case for profiles_post

        Save user profile
        """
        pass

    def test_reminders_get(self) -> None:
        """Test case for reminders_get

        List or retrieve reminders
        """
        pass

    def test_reminders_post(self) -> None:
        """Test case for reminders_post

        Save reminder
        """
        pass

    def test_reports_get(self) -> None:
        """Test case for reports_get

        Generate report
        """
        pass


if __name__ == '__main__':
    unittest.main()
