# coding: utf-8

"""
    Diabetes Assistant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.models.reminder_type import ReminderType

class TestReminderType(unittest.TestCase):
    """ReminderType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReminderType(self):
        """Test ReminderType"""
        # inst = ReminderType()

if __name__ == '__main__':
    unittest.main()
