# coding: utf-8

"""
    Diabetes Assistant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.models.user_context import UserContext

class TestUserContext(unittest.TestCase):
    """UserContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserContext:
        """Test UserContext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserContext`
        """
        model = UserContext()
        if include_optional:
            return UserContext(
                id = 56,
                first_name = '',
                last_name = '',
                username = '',
                language_code = '',
                is_premium = True
            )
        else:
            return UserContext(
                id = 56,
        )
        """

    def testUserContext(self):
        """Test UserContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
