# coding: utf-8

"""
    Diabetes Assistant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_reminders_post_reminders_post(self) -> None:
        """Test case for api_reminders_post_reminders_post

        Api Reminders Post
        """
        pass

    def test_api_reminders_reminders_get(self) -> None:
        """Test case for api_reminders_reminders_get

        Api Reminders
        """
        pass

    def test_create_user_user_post(self) -> None:
        """Test case for create_user_user_post

        Create User
        """
        pass

    def test_delete_history_history_record_id_delete(self) -> None:
        """Test case for delete_history_history_record_id_delete

        Delete History
        """
        pass

    def test_get_analytics_analytics_get(self) -> None:
        """Test case for get_analytics_analytics_get

        Get Analytics
        """
        pass

    def test_get_history_history_get(self) -> None:
        """Test case for get_history_history_get

        Get History
        """
        pass

    def test_get_stats_stats_get(self) -> None:
        """Test case for get_stats_stats_get

        Get Stats
        """
        pass

    def test_get_timezone_timezone_get(self) -> None:
        """Test case for get_timezone_timezone_get

        Get Timezone
        """
        pass

    def test_post_history_history_post(self) -> None:
        """Test case for post_history_history_post

        Post History
        """
        pass

    def test_profile_self_profile_self_get(self) -> None:
        """Test case for profile_self_profile_self_get

        Profile Self
        """
        pass

    def test_profiles_get_profiles_get(self) -> None:
        """Test case for profiles_get_profiles_get

        Profiles Get
        """
        pass

    def test_profiles_post_profiles_post(self) -> None:
        """Test case for profiles_post_profiles_post

        Profiles Post
        """
        pass

    def test_put_timezone_timezone_put(self) -> None:
        """Test case for put_timezone_timezone_put

        Put Timezone
        """
        pass


if __name__ == '__main__':
    unittest.main()
