# coding: utf-8

"""
    Diabetes Assistant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.models.entries_get200_response import EntriesGet200Response

class TestEntriesGet200Response(unittest.TestCase):
    """EntriesGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntriesGet200Response:
        """Test EntriesGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntriesGet200Response`
        """
        model = EntriesGet200Response()
        if include_optional:
            return EntriesGet200Response(
                telegram_id = 56,
                id = 56,
                event_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                photo_path = '',
                carbs_g = 1.337,
                xe = 1.337,
                sugar_before = 1.337,
                dose = 1.337,
                gpt_summary = ''
            )
        else:
            return EntriesGet200Response(
                telegram_id = 56,
                event_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testEntriesGet200Response(self):
        """Test EntriesGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
