# coding: utf-8

"""
Diabetes Assistant API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from diabetes_sdk.models.reminder_schema import ReminderSchema


class TestReminderSchema(unittest.TestCase):
    """ReminderSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReminderSchema:
        """Test ReminderSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ReminderSchema`
        """
        model = ReminderSchema()
        if include_optional:
            return ReminderSchema(
                telegram_id = 56,
                id = 56,
                type = '',
                time = '',
                interval_hours = 56,
                minutes_after = 56,
                is_enabled = True,
                org_id = 56
            )
        else:
            return ReminderSchema(
                telegram_id = 56,
                type = '',
        )
        """

    def testReminderSchema(self):
        """Test ReminderSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
