"""change description

Revision ID: 20250903_change_description
Revises: 20250903_add_timezone_auto_to_users
Create Date: 2025-08-31 10:37:36.590628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20250903_change_description"
down_revision: Union[str, None] = "20250903_add_timezone_auto_to_users"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alerts",
        "ts",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("alerts", "resolved", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index("ix_alerts_org_id", table_name="alerts")
    op.alter_column(
        "entries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_entries_org_id", table_name="entries")
    op.create_index(
        op.f("ix_history_records_id"), "history_records", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_history_records_telegram_id"),
        "history_records",
        ["telegram_id"],
        unique=False,
    )
    op.alter_column(
        "profiles", "sos_alerts_enabled", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_index("ix_profiles_org_id", table_name="profiles")
    op.add_column("reminder_logs", sa.Column("org_id", sa.Integer(), nullable=True))
    op.alter_column(
        "reminder_logs",
        "event_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "reminders",
        "title",
        existing_type=sa.TEXT(),
        server_default=None,
        type_=sa.String(),
        nullable=True,
    )
    op.alter_column(
        "reminders", "is_enabled", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "reminders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_reminders_org_id", table_name="reminders")
    op.drop_index("ix_reminders_owner_enabled", table_name="reminders")
    op.create_index(op.f("ix_timezones_id"), "timezones", ["id"], unique=False)
    op.alter_column(
        "users", "onboarding_complete", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column("users", "plan", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "timezone_auto",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_users_org_id", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_users_org_id", "users", ["org_id"], unique=False)
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "timezone_auto",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'UTC'::character varying"),
        existing_nullable=False,
    )
    op.alter_column("users", "plan", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users", "onboarding_complete", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_index(op.f("ix_timezones_id"), table_name="timezones")
    op.create_index(
        "ix_reminders_owner_enabled",
        "reminders",
        ["telegram_id", "is_enabled"],
        unique=False,
    )
    op.create_index("ix_reminders_org_id", "reminders", ["org_id"], unique=False)
    op.alter_column(
        "reminders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "reminders", "is_enabled", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "reminders",
        "title",
        existing_type=sa.String(),
        server_default=sa.text("''::text"),
        type_=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "reminder_logs",
        "event_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("reminder_logs", "org_id")
    op.create_index("ix_profiles_org_id", "profiles", ["org_id"], unique=False)
    op.alter_column(
        "profiles", "sos_alerts_enabled", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_index(op.f("ix_history_records_telegram_id"), table_name="history_records")
    op.drop_index(op.f("ix_history_records_id"), table_name="history_records")
    op.create_index("ix_entries_org_id", "entries", ["org_id"], unique=False)
    op.alter_column(
        "entries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("ix_alerts_org_id", "alerts", ["org_id"], unique=False)
    op.alter_column("alerts", "resolved", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "alerts",
        "ts",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
