"""squashed initial

Revision ID: 20250807_squashed_initial
Revises:
Create Date: 2025-08-07 09:15:17.518654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from typing import Any, cast


# revision identifiers, used by Alembic.
revision: str = "20250807_squashed_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default="UTC",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default="UTC",
    )
    # ### end Alembic commands ###
