name: OpenAPI Check

on:
  push:
    paths:
      - 'libs/contracts/openapi.yaml'
  pull_request:
    paths:
      - 'libs/contracts/openapi.yaml'
  workflow_dispatch:

jobs:
  oasdiff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Fetch main openapi.yaml
        run: |
          git fetch origin main
          git show origin/main:libs/contracts/openapi.yaml > /tmp/openapi_main.yaml

      - name: Run oasdiff breaking change check
        run: |
          docker run --rm -v "$PWD:/work" ghcr.io/tufin/oasdiff:latest \
            breaking /tmp/openapi_main.yaml libs/contracts/openapi.yaml \
            --fail-on-diff
