# file: .github/workflows/openapi-check.yml
name: OpenAPI Check

on:
  push:
    paths:
      - 'libs/contracts/openapi.yaml'
  pull_request:
    paths:
      - 'libs/contracts/openapi.yaml'
  workflow_dispatch:

jobs:
  oasdiff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Проверка, что openapi.yaml валиден для oasdiff (запуск контейнера с Docker Hub)
      - name: Run oasdiff (Docker Hub)
        run: |
          docker run --rm -v "$PWD:/work" \
            tufin/oasdiff:latest \
            /work/libs/contracts/openapi.yaml
