# file: .github/workflows/openapi-check.yml
name: OpenAPI Check

on:
  push:
    paths:
      - 'libs/contracts/openapi.yaml'
  workflow_dispatch:

jobs:
  oasdiff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Run oasdiff
        run: |
          docker run --rm \
            -v "$PWD:/work" \
            ghcr.io/tufin/oasdiff:latest \
            /work/libs/contracts/openapi.yaml
