# file: .github/workflows/pr-auto-assign.yml
name: PR Auto-Assign

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewers
        uses: wow-actions/auto-assign@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            offonar
      - name: Add webapp-sync label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: webapp-sync
