name: Generate SDKs

on:
  push:
    paths:
      - 'libs/contracts/openapi.yaml'
  pull_request:
    paths:
      - 'libs/contracts/openapi.yaml'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install
      - name: Generate SDKs
        run: pnpm run generate:sdk
      - name: Commit SDKs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: regenerate SDKs'
          file_pattern: |
            libs/ts-sdk/**
            libs/py-sdk/**
